### ISSUE TITLE
Issue in building moveback recovery 

### ISSUE THREAD

**Issue by shivamtrip** [Auxilio-Robotics/alfred-autonomy#17]
Issue: 
When cloning alfred_autonomy repository (or even just alfred_navigation package), there is an issue with building it. The error message during building says that while building alfred_navigation, it 'failed to load a plugin, MovebackRecovery'.  

Temporary Workaround: 
Copy libmoveback_recovery.so from devel folder (root) of another built alfred_autonomy repository and paste it into devel folder (root) of new alfred_autonomy repository. 

It should then be able to load the plugin and work!

How was it built for the first time (when there was no prior .so file)??
--> Try building it and it will fail in one of the lines. We can comment out those lines and it will rebuild successfully. Then we can uncomment those lines and it should work as follows

**Comment by praveenVnktsh** [comment]
Fixed. Issue was that the library was being built very high up in CMake (in cmakelists.txt) and thus had nothing attached to it. Pushed it to build just before installing and it builds correctly. Also added releevant installation libraries in setup_robot script.

Updated in branch fvd_encore.

It is also possible that move-back recovery was not working properly due to this issue. testing required.
